### ISSUE TITLE
Permissive License

### ISSUE THREAD

**Issue by sirinath** [Quantler/Core#2]
Can you consider moving to a more permissive license like BSD, MIT, ASL 2.0?

**Comment by MHamburg** [comment]
Hi Sirinath,

Could you give us more context how the current license is insufficient for your needs?

**Comment by sirinath** [comment]
In the context of outsourcing many organisations have a limited whitelisted set of licenses. Most universally whitelisted are: BSD, MIT, ASL 2.0

**Comment by MHamburg** [comment]
Using the current LGPL license you are allowed to use the source code in a closed source environment. The only difference here in relationship to BSD is that you are obligated to open source any changes made in the library: Quantler.

For more information:
http://daisy-trac.cvsdude.com/tobi/wiki/LGPLvsBSD

To answer your question whether or not we will consider moving the license, no we will not.

**Comment by sirinath** [comment]
Yes. I understand. But what this is dictated by the clients. *GPL is constantly also due to legal validations.
